#!/usr/bin/env python3
"""Phase-0 number audit: recompute the manuscript's E5 numbers from the raw records.

This is deliberately *not* a re-run of ``make_numbers.py``. Re-running the generator against
its own output proves only that the generator is deterministic. Everything below is recomputed
from ``results/e5/raw/e5_runs.json`` by independent code, and only then compared against the
macros the manuscript actually uses.

Emits ``docs/current_number_audit.md``.

Run: ``python scripts/audit_phase0.py``
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

RAW = ROOT / "results" / "e5" / "raw" / "e5_runs.json"
NUMBERS = ROOT / "paper" / "generated" / "numbers.tex"
OUT = ROOT / "docs" / "current_number_audit.md"

READOUTS = ("pinv", "wout", "ls")


def macros() -> Dict[str, str]:
    pat = re.compile(r"\\newcommand\{\\([A-Za-z]+)\}\{([^}]*)\}")
    return dict(pat.findall(NUMBERS.read_text(encoding="utf-8")))


def s95_from_rows(rows: List[Dict[str, Any]], key: str, level: float = 0.95) -> int:
    """Independent reimplementation: largest s with a contiguous prefix at or above `level`."""
    best = 0
    for r in sorted(rows, key=lambda x: x["s"]):
        if r[key] >= level:
            best = int(r["s"])
        else:
            break
    return best


def main() -> int:
    d = json.loads(RAW.read_text(encoding="utf-8"))
    runs = d["runs"]
    primary = d["primary_train_sparsity"]
    M = macros()
    lines: List[str] = []
    findings: List[str] = []

    def w(s: str = "") -> None:
        lines.append(s)

    def check(name: str, recomputed: Any, fmt: str = "{:.4f}") -> bool:
        """Compare a recomputed value against the macro of the same name."""
        if name not in M:
            findings.append(f"macro `{name}` referenced by the audit does not exist")
            return False
        want = M[name]
        got = fmt.format(recomputed) if not isinstance(recomputed, str) else recomputed
        ok = want == got
        w(f"| `{name}` | {want} | {got} | {'OK' if ok else '**MISMATCH**'} |")
        if not ok:
            findings.append(f"macro `{name}`: manuscript {want}, recomputed {got}")
        return ok

    w("# Phase-0 number audit — E5 recomputed from raw records")
    w()
    w("Generated by `scripts/audit_phase0.py`. Every value in the *recomputed* column is derived")
    w("from `results/e5/raw/e5_runs.json` by code independent of `scripts/make_numbers.py`.")
    w()
    w(f"Source: `{RAW.relative_to(ROOT).as_posix()}` — {len(runs)} runs, "
      f"primary training sparsity {primary}.")
    w()

    # ---------------------------------------------------------------- seedwise s95
    w("## 1. Seedwise `s95`, per cell")
    w()
    w("The stored `s95_*` fields are recomputed from the recovery curves in `rows`, to check")
    w("that the summary matches the data it summarises.")
    w()
    w("| cell | decoder | stored | recomputed from rows | agree |")
    w("|---|---|---|---|---|")
    stored_ok = True
    for kind in ("L4", "L2", "random"):
        for p in sorted({r["p_train"] for r in runs if r["loss_kind"] == kind}):
            sub = [r for r in runs if r["loss_kind"] == kind and r["p_train"] == p]
            for key, col in [("s95_model", "p_rec_model")] + \
                            [(f"s95_linear_{ro}", f"p_rec_linear_{ro}") for ro in READOUTS]:
                stored = [int(r[key]) for r in sub]
                recomp = [s95_from_rows(r["rows"], col) for r in sub]
                agree = stored == recomp
                stored_ok &= agree
                w(f"| {kind} p={p} | `{key}` | {stored} | {recomp} | "
                  f"{'OK' if agree else '**MISMATCH**'} |")
    w()
    if not stored_ok:
        findings.append("stored s95 fields disagree with the recovery curves")

    # ------------------------------------------------- the two contested s95 claims
    w("## 2. The two `s95` claims the manuscript makes in prose")
    w()
    l4p = [r for r in runs if r["loss_kind"] == "L4" and r["p_train"] == primary]
    l4s = [r for r in runs if r["loss_kind"] == "L4" and r["p_train"] != primary]

    def best_linear(r):
        return max(int(r[f"s95_linear_{ro}"]) for ro in READOUTS)

    w(f"**Primary sparsity p={primary}.** Claim: the best linear readout is strictly ahead of the")
    w("network on every seed.")
    w()
    w("| seed | s95(model) | s95(pinv) | s95(wout) | s95(ls) | best linear | linear ahead |")
    w("|---|---|---|---|---|---|---|")
    all_ahead = True
    for r in sorted(l4p, key=lambda x: x["seed"]):
        bl = best_linear(r)
        ahead = bl > int(r["s95_model"])
        all_ahead &= ahead
        w(f"| {r['seed']} | {r['s95_model']} | {r['s95_linear_pinv']} | {r['s95_linear_wout']} "
          f"| {r['s95_linear_ls']} | {bl} | {'yes' if ahead else '**no**'} |")
    w()
    w(f"Verdict: strictly ahead on **{sum(best_linear(r) > int(r['s95_model']) for r in l4p)} "
      f"of {len(l4p)}** seeds. Manuscript says all of them: "
      f"{'**consistent**' if all_ahead else '**INCONSISTENT**'}.")
    w()
    if not all_ahead:
        findings.append(f"the 'ahead on all seeds at p={primary}' claim is not supported")

    secondary_p = l4s[0]["p_train"] if l4s else None
    w(f"**Secondary sparsity p={secondary_p}.** This is the claim the external review flagged as")
    w("false in an earlier draft (`W_out` allegedly `s95=4` on every seed).")
    w()
    w("| seed | s95(model) | s95(pinv) | s95(wout) | s95(ls) | best linear |")
    w("|---|---|---|---|---|---|")
    for r in sorted(l4s, key=lambda x: x["seed"]):
        w(f"| {r['seed']} | {r['s95_model']} | {r['s95_linear_pinv']} | {r['s95_linear_wout']} "
          f"| {r['s95_linear_ls']} | {best_linear(r)} |")
    wout_vals = [int(r["s95_linear_wout"]) for r in l4s]
    ahead_n = sum(best_linear(r) > int(r["s95_model"]) for r in l4s)
    w()
    w(f"`s95(wout)` across seeds: {wout_vals}. Constant at 4: "
      f"**{'yes' if set(wout_vals) == {4} else 'NO — the original claim was false'}**.")
    w(f"Best linear strictly ahead of the network on **{ahead_n} of {len(l4s)}** seeds.")
    w()
    w("| macro | manuscript | recomputed | status |")
    w("|---|---|---|---|")
    check("EfiveLfourSlinAheadSecondary", str(ahead_n))
    check("EfiveLfourSlinBestMax", str(max(best_linear(r) for r in l4p)))
    check("EfiveLfourSmodelMax", str(max(int(r["s95_model"]) for r in l4p)))
    w()

    # ------------------------------------------------- readout attribution of ratios
    w("## 3. Attribution of every attainment ratio")
    w()
    w("Mixing readouts across a comparison was a real defect in an earlier draft. Each macro is")
    w("recomputed from the readout its name claims.")
    w()
    w("| macro | manuscript | recomputed | status |")
    w("|---|---|---|---|")
    sel = [r for r in runs if r["loss_kind"] == "random" or r["p_train"] == primary]
    for kind, tag in (("L4", "Lfour"), ("L2", "Ltwo"), ("random", "Rand")):
        sub = [r for r in sel if r["loss_kind"] == kind]
        for ro, rtag in (("ls", "Ls"), ("pinv", "Pinv"), ("wout", "Wout")):
            name = f"Efive{tag}Ratio{rtag}Mean"
            if name not in M:
                continue
            vals = [r["floor_stats"][ro]["ratio_mean_sq"] for r in sub
                    if "ratio_mean_sq" in r["floor_stats"][ro]]
            check(name, float(np.mean(vals)))
        if kind == "L4":
            for ro, rtag in (("pinv", "Pinv"), ("ls", "Ls")):
                vals = [r["floor_stats"][ro]["ratio_mean_sq"] for r in sub]
                check(f"Efive{tag}Ratio{rtag}Min", float(np.min(vals)))
                check(f"Efive{tag}Ratio{rtag}Max", float(np.max(vals)))
    w()

    # ------------------------------------------------- recovery rates quoted in prose
    w("## 4. Recovery rates quoted in the results section")
    w()
    w("| macro | manuscript | recomputed | status |")
    w("|---|---|---|---|")
    word = {3: "Three", 4: "Four", 5: "Five", 6: "Six"}
    for s in (3, 4, 5, 6):
        rows = [next(x for x in r["rows"] if x["s"] == s) for r in l4p]
        check(f"EfiveLfourPmodel{word[s]}", float(np.mean([x["p_rec_model"] for x in rows])),
              "{:.3f}")
        if s != 3:
            check(f"EfiveLfourPlin{word[s]}",
                  float(np.mean([max(x[f"p_rec_linear_{ro}"] for ro in READOUTS) for x in rows])),
                  "{:.3f}")
        else:
            check("EfiveLfourRmsThree",
                  float(np.mean([min(x[f"linear_rms_{ro}"] for ro in READOUTS) for x in rows])))
            check("EfiveLfourFloorThree", float(rows[0]["rms_floor_uniform"]))
    w()

    # ------------------------------------------------- floor never violated
    w("## 5. Structural checks")
    w()
    viol = [(r["loss_kind"], r["seed"], ro) for r in runs for ro in READOUTS
            if r["floor_stats"][ro].get("violates_floor")]
    below = [(r["loss_kind"], r["seed"], ro, r["floor_stats"][ro]["ratio_mean_sq"])
             for r in runs for ro in READOUTS
             if r["floor_stats"][ro].get("ratio_mean_sq", 1.0) < 1.0]
    w(f"- Floor violations flagged across {len(runs)}x{len(READOUTS)} interfaces: "
      f"**{len(viol)}** {viol if viol else ''}")
    w(f"- Attainment ratios below 1: **{len(below)}** {below if below else ''}")
    if viol or below:
        findings.append("an attainment ratio falls below the floor")

    energy_bad = [(r["loss_kind"], r["seed"], ro, x["s"])
                  for r in runs for x in r["rows"] for ro in READOUTS
                  if x[f"linear_energy_{ro}"] < x["energy_floor_uniform"] * (1 - 1e-9)]
    w(f"- Rows below the uniform-support energy floor: **{len(energy_bad)}** "
      f"{energy_bad[:5] if energy_bad else ''}")
    if energy_bad:
        findings.append("a linear energy falls below the proved uniform-support floor")

    paired = all(x["trials"] == r["trials"] for r in runs for x in r["rows"])
    w(f"- Network and linear interfaces evaluated on the same trial count per row: "
      f"**{'yes' if paired else 'no'}**")
    w()

    # ------------------------------------------------- summary
    w("## 6. Findings")
    w()
    if findings:
        for f in findings:
            w(f"- **{f}**")
    else:
        w("No discrepancy found between the manuscript's E5 macros and an independent")
        w("recomputation from the raw records.")
    w()
    w("### Known limitations of this audit")
    w()
    w("- It covers E5 only. E1-E4 and E6 macros are checked for existence and traceability by")
    w("  `scripts/check_manuscript_numbers.py`, not recomputed here.")
    w("- It cannot detect an error that is present in both the raw records and the manuscript,")
    w("  i.e. a bug in the experiment rather than in the reporting. Those are addressed by the")
    w("  protocol audit in `current_claim_audit.md`.")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT).as_posix()}")
    print(f"findings: {len(findings)}")
    for f in findings:
        print(f"  - {f}")
    return 1 if findings else 0


if __name__ == "__main__":
    raise SystemExit(main())
