#!/usr/bin/env python3
"""Verify that every measured number in the manuscript comes from the saved results.

Four checks, all of which must pass (exit code 0):

1. ``paper/generated/numbers.tex`` is byte-identical to what
   ``scripts/make_numbers.py`` produces from the current contents of ``results/``.
2. Every generated table under ``paper/tables/`` is byte-identical to what
   ``scripts/make_tables.py`` produces from the same results.
3. Every macro the manuscript uses that belongs to a generated family is actually defined.
4. No macro is defined but unused (a stale macro usually means a claim was deleted from the
   text while its number was left behind).

Checks 2 and 3 exist because an external reproduction audit broke this script twice. Writing
``9.999`` over a real number in a generated table left it green, because it only ever read
``main.tex`` and the tables are ``\\input`` at compile time. And an undefined ``\\EeightBogus`` in
the manuscript left it green, because the undefined-macro test ran against a hardcoded list of eight
name prefixes that predated the accelerator campaigns -- so it covered none of Section 10.5, which
is where all the new work is. The prefix list is now derived from the generated file itself, so a
new macro family cannot silently fall outside the check.

The script also reports, without failing, decimal literals in the results and limitations sections.
Those cannot be verified automatically, and every one of them is a number a human has to justify:
the same audit found four quoted from an artefact that was never committed.

Run:  ``python scripts/check_manuscript_numbers.py``
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))

from make_numbers import OUT, build  # noqa: E402

PAPER = REPO_ROOT / "paper"
TEX_SOURCES = ["tmlr.tex"]
DEFINE_RE = re.compile(r"\\newcommand\{\\([A-Za-z]+)\}")
USE_RE = re.compile(r"\\([A-Za-z]+)(?![A-Za-z])")


def main() -> int:
    failures: list[str] = []

    # ---- 1. the generated file matches the results ----
    if not OUT.exists():
        print(f"FAIL: {OUT.relative_to(REPO_ROOT)} does not exist; run scripts/make_numbers.py")
        return 1
    on_disk = OUT.read_text(encoding="utf-8")
    regenerated = build().render()
    if on_disk != regenerated:
        failures.append(
            "generated/numbers.tex is out of date with respect to results/; "
            "re-run scripts/make_numbers.py")
        d_disk = dict(DEFINE_RE.findall(on_disk) and
                      re.findall(r"\\newcommand\{\\([A-Za-z]+)\}\{([^}]*)\}", on_disk))
        d_new = dict(re.findall(r"\\newcommand\{\\([A-Za-z]+)\}\{([^}]*)\}", regenerated))
        for k in sorted(set(d_disk) | set(d_new)):
            if d_disk.get(k) != d_new.get(k):
                failures.append(f"    {k}: file={d_disk.get(k)!r} results={d_new.get(k)!r}")
    defined = set(re.findall(r"\\newcommand\{\\([A-Za-z]+)\}", regenerated))
    print(f"checked {len(defined)} generated macros")

    # ---- 2. the generated tables match the results ----
    # make_tables writes to disk, so its writer is captured rather than run: comparing in memory
    # means a stale table is reported instead of being quietly overwritten by the check itself.
    import make_tables  # noqa: E402

    produced: dict[str, str] = {}
    real_write = make_tables.write

    def capture(name: str, lines: list[str]) -> None:
        header = "% Generated by scripts/make_tables.py from results/. Do not edit by hand.\n"
        produced[name] = header + "\n".join(lines) + "\n"

    make_tables.write = capture
    try:
        make_tables.main()
    finally:
        make_tables.write = real_write
    for name, want in sorted(produced.items()):
        path = PAPER / "tables" / f"{name}.tex"
        if not path.exists():
            failures.append(f"generated table {path.relative_to(REPO_ROOT)} is missing")
        elif path.read_text(encoding="utf-8") != want:
            failures.append(
                f"paper/tables/{name}.tex does not match results/; re-run scripts/make_tables.py")
    print(f"checked {len(produced)} generated tables")

    # ---- 2 and 3. the manuscript uses exactly the macros that are defined ----
    text = ""
    for name in TEX_SOURCES:
        path = PAPER / name
        if not path.exists():
            failures.append(f"manuscript source {path.relative_to(REPO_ROOT)} not found")
            continue
        text += path.read_text(encoding="utf-8")
    for extra in sorted((PAPER / "sections").glob("*.tex")) if (PAPER / "sections").exists() else []:
        text += extra.read_text(encoding="utf-8")

    used = set(USE_RE.findall(text)) & defined

    # A used macro belongs to a generated family if it shares a prefix of at least FAMILY_CHARS
    # characters with some defined macro. Derived from the generated file rather than hardcoded, so
    # a new family (Eeight, Prim, Sc, Margin, ...) is covered the moment its first macro exists --
    # the hardcoded list stopped at Esix and left every accelerator-campaign macro unchecked.
    FAMILY_CHARS = 4
    prefixes = {d[:n] for d in defined for n in range(FAMILY_CHARS, len(d) + 1)}
    undefined_used = {m for m in USE_RE.findall(text)
                      if len(m) > FAMILY_CHARS and m[:FAMILY_CHARS] in
                      {p[:FAMILY_CHARS] for p in prefixes}} - defined
    if undefined_used:
        failures.append(f"manuscript uses undefined generated macros: {sorted(undefined_used)}")
    unused = defined - used
    if unused:
        failures.append(f"generated macros never used in the manuscript: {sorted(unused)}")

    print(f"manuscript uses {len(used)} of them")

    # ---- reported, never fatal: decimal literals a human has to justify ----
    # Two or more decimal places, because the theory's own constants are 1/2, 3/2, 0.5 and would
    # otherwise drown the signal. This cannot know whether a literal is a measurement, so it does
    # not fail; it prints a list. The audit that prompted it found four numbers quoted from an
    # artefact that was never committed, sitting in a limitation, invisible to every other check.
    literal_re = re.compile(r"(?<![\d.])\d+\.\d{2,}(?![\d])")
    scanned = [PAPER / n for n in TEX_SOURCES if (PAPER / n).exists()]
    scanned += sorted((PAPER / "sections").glob("*.tex"))
    literals = []
    for path in scanned:
        rel = path.relative_to(PAPER).as_posix()
        for i, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            code = line.split("%")[0] if not line.lstrip().startswith("%") else ""
            code = re.sub(r"\\(cite|label|ref|input|includegraphics)\{[^}]*\}", "", code)
            for hit in literal_re.findall(code):
                literals.append((rel, i, hit))
    if literals:
        print(f"\nnote: {len(literals)} decimal literal(s) across {len(scanned)} source file(s) "
              f"are not generated macros, so nothing verifies them:")
        for rel, i, hit in literals:
            print(f"  {rel}:{i}: {hit}")

    if failures:
        print("\nFAILURES:")
        for f in failures:
            print(" -", f)
        return 1
    print("OK: every measured number in the manuscript traces to results/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
