#!/usr/bin/env python3
"""Regenerate every manuscript table from the raw result files.

Tables are written as ``booktabs`` fragments under ``paper/tables/`` and are
included with ``\\input``. No cell is typed by hand.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict, List

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
RESULTS = REPO_ROOT / "results"
TABDIR = REPO_ROOT / "paper" / "tables"


def load(rel: str) -> Any:
    path = RESULTS / rel
    if not path.exists():
        raise SystemExit(f"missing results file {path}; run the corresponding campaign first")
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def write(name: str, lines: List[str]) -> None:
    TABDIR.mkdir(parents=True, exist_ok=True)
    path = TABDIR / f"{name}.tex"
    header = ("% Generated by scripts/make_tables.py from results/. Do not edit by hand.\n")
    path.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {path.relative_to(REPO_ROOT)}")


def table_e1() -> None:
    rows = load("e1/raw/e1_rows.json")["rows"]
    ratios = sorted({r["ratio"] for r in rows})
    ds = sorted({r["d"] for r in rows})
    out = [r"\begin{tabular}{r" + "r" * len(ratios) + r"}", r"\toprule",
           r"& \multicolumn{%d}{c}{$F/d$} \\" % len(ratios),
           r"\cmidrule(lr){2-%d}" % (len(ratios) + 1),
           "$d$ & " + " & ".join(str(r) for r in ratios) + r" \\", r"\midrule"]
    for d in ds:
        cells = []
        for rt in ratios:
            r = next((x for x in rows if x["d"] == d and x["ratio"] == rt), None)
            cells.append(f"{r['tied_ratio_mean_sq_mean']:.3f}" if r else "--")
        out.append(f"{d} & " + " & ".join(cells) + r" \\")
    out += [r"\bottomrule", r"\end{tabular}"]
    write("tab_e1_floor", out)


def table_e4() -> None:
    e4 = load("e4/raw/e4_runs.json")
    s = e4["summary"]
    order = [("free", "free ($G$, $\\Phi$ independent)"),
             ("tied", "tied ($G=\\Phi^{\\top}$)"),
             ("softmax", "smooth-max"),
             ("uncalibrated", "uncalibrated (ablation)")]
    out = [r"\begin{tabular}{lrrrrr}", r"\toprule",
           r"variant & runs & mean $\widehat{W}/W$ & max $\widehat{W}/W$ & "
           r"below floor & extra \\", r"\midrule"]
    for key, label in order:
        e = s[key]
        if key == "tied":
            extra = fr"$\rho_{{\max}}={e['tight_frame_residual_max']:.4f}$"
            mean, mx = f"{e['ratio_mean_sq_mean']:.4f}", f"{e['ratio_mean_sq_max']:.4f}"
        elif key == "softmax":
            extra = fr"$\max$ ratio $={e['ratio_max_mean']:.2f}$"
            mean, mx = f"{e['ratio_mean_sq_mean']:.4f}", f"{e['ratio_mean_sq_max']:.4f}"
        elif key == "uncalibrated":
            extra = (fr"raw ratio $\geq{e['ratio_mean_sq_raw_min']:.1e}$, "
                     fr"$\min|M_{{ii}}|={e['diag_gain_min_abs_min']:.1e}$")
            mean = mx = r"\multicolumn{1}{c}{--}"
            mean, mx = "n/a", "n/a"
        else:
            extra = "--"
            mean, mx = f"{e['ratio_mean_sq_mean']:.4f}", f"{e['ratio_mean_sq_max']:.4f}"
        out.append(f"{label} & {e['n_runs']} & {mean} & {mx} & {e['n_below_floor']} & {extra} "
                   + r"\\")
    out += [r"\bottomrule", r"\end{tabular}"]
    write("tab_e4_variants", out)


def table_e5() -> None:
    e5 = load("e5/raw/e5_runs.json")
    primary = e5["primary_train_sparsity"]
    sel = [r for r in e5["runs"] if r["loss_kind"] == "random" or r["p_train"] == primary]
    labels = {"L4": r"$L^4$-trained", "L2": r"$L^2$-trained", "random": "random code"}
    out = [r"\begin{tabular}{lrrrrr}", r"\toprule",
           r"model & $\widehat{W}/W$ & $s_{95}$ (network) & $s_{95}$ (best linear) & "
           r"ReLU clipped (\%) & agrees with linear (\%) \\", r"\midrule"]
    for kind in ("L4", "L2", "random"):
        sub = [r for r in sel if r["loss_kind"] == kind]
        if not sub:
            continue
        ratios = [r["floor_stats"]["ls"]["ratio_mean_sq"] for r in sub
                  if "ratio_mean_sq" in r["floor_stats"]["ls"]]
        s95m = [r["s95_model"] for r in sub]
        s95l = [max(r[f"s95_linear_{ro}"] for ro in ("pinv", "wout", "ls")) for r in sub]
        lin = [r["linearity"] for r in sub]
        out.append(
            f"{labels[kind]} & {np.mean(ratios):.3f} & "
            f"{np.mean(s95m):.1f} & {np.mean(s95l):.1f} & "
            f"{100 * np.mean([x['frac_relu_clipped'] for x in lin]):.1f} & "
            f"{100 * np.mean([x['decision_agreement_with_linear'] for x in lin]):.1f}" + r" \\")
    out += [r"\bottomrule", r"\end{tabular}"]
    write("tab_e5_interface", out)


def table_e6() -> None:
    e6 = load("e6/raw/e6_summary.json")
    per_d = sorted(e6["per_d"], key=lambda e: e["d"])
    out = [r"\begin{tabular}{rrrrrr}", r"\toprule",
           r"$d$ & $F=d^2$ & trials & $s_{95}$ & $d/(16\ln d)$ & wall clock (min) \\",
           r"\midrule"]
    for e in per_d:
        out.append(fr"{e['d']} & {e['F']:,} & {e['trials']} & {e['s95']} & "
                   fr"{e['reference_union_bound']:.2f} & {e['duration_seconds'] / 60:.1f} \\"
                   .replace(",", r"\,"))
    out += [r"\bottomrule", r"\end{tabular}"]
    write("tab_e6_scaling", out)


TRACE_ROWS = [
    ("The floor is respected by every calibrated interface", "Tab.~\\ref{tab:e1}, Fig.~\\ref{fig:overview}a",
     "results/e1/raw/e1\\_rows.json", "configs/e1.json", "experiments/e1\\_welch\\_floor.py",
     "python experiments/e1\\_welch\\_floor.py"),
    ("Threshold recovery succeeds where linear readout cannot be exact",
     "Fig.~\\ref{fig:overview}b", "results/e2/raw/e2\\_profiles.json", "configs/e2.json",
     "experiments/e2\\_threshold\\_recovery.py", "python experiments/e2\\_threshold\\_recovery.py"),
    ("Average linear energy follows the $s/d$ scale", "Fig.~\\ref{fig:overview}c",
     "results/e3/raw/e3\\_rows.json", "configs/e3.json", "experiments/e3\\_linear\\_energy.py",
     "python experiments/e3\\_linear\\_energy.py"),
    ("Learned codes attain the floor", "Tab.~\\ref{tab:e4}, Fig.~\\ref{fig:e4}",
     "results/e4/raw/e4\\_runs.json", "configs/e4.json", "experiments/e4\\_optimized\\_codes.py",
     "python experiments/e4\\_optimized\\_codes.py"),
    ("A trained network attains the floor and separates the two criteria",
     "Tab.~\\ref{tab:e5}, Fig.~\\ref{fig:e5}", "results/e5/raw/e5\\_runs.json", "configs/e5.json",
     "experiments/e5\\_trained\\_toy.py", "python experiments/e5\\_trained\\_toy.py"),
    ("$s_{95}(d)$ grows with the $d/\\ln d$ scale", "Tab.~\\ref{tab:e6}, Fig.~\\ref{fig:e6}",
     "results/e6/raw/e6\\_summary.json", "configs/e6.json",
     "experiments/e6\\_threshold\\_scaling.py", "python experiments/e6\\_threshold\\_scaling.py"),
]


def table_traceability() -> None:
    out = [r"\begin{tabular}{p{3.5cm}p{2.3cm}p{3.4cm}p{3.6cm}}", r"\toprule",
           r"claim & figure / table & raw result file & script (config) \\", r"\midrule"]
    for claim, where, resfile, cfg, script, _cmd in TRACE_ROWS:
        out.append(fr"{claim} & {where} & \texttt{{\small {resfile}}} & "
                   fr"\texttt{{\small {script}}} (\texttt{{\small {cfg}}}) \\")
        out.append(r"\addlinespace[2pt]")
    out += [r"\bottomrule", r"\end{tabular}"]
    write("tab_traceability", out)


def table_cost() -> None:
    out = [r"\begin{tabular}{llrrlr}", r"\toprule",
           r"campaign & question & jobs & workers & device & wall clock (min) \\", r"\midrule"]
    meta = {
        "e1": ("E1", "floor on random codes"),
        "e2": ("E2", "recovery at $F=d^2$"),
        "e3": ("E3", "average linear energy"),
        "e4": ("E4", "optimised codes"),
        "e5": ("E5", "trained toy model"),
        "e6": ("E6", "scaling to $d=1024$"),
    }
    # The accelerator campaigns, in the order the paper introduces them. `jobs` is the number of
    # models rather than a config field, because that is the quantity a reader wants to divide the
    # wall clock by. `dagger` marks a duration the run record undercounts: --resume times only the
    # final invocation, so stage A's figure is the last leg and not the campaign.
    gpu = [
        ("e7", "E7-A", "trained-network grid", "cell_*.json", True),
        ("e7_stageB", "E7-B", "feature load and sparsity", "cell_*.json", False),
        ("e7_stageC", "E7-C", "$d=400$ frontier rate", "cell_*.json", False),
        ("e8", "E8", "frozen code vs frozen readout", "e8_runs.json", False),
        ("e8_d200", "E8", "the same at $d=200$", "e8_runs.json", False),
    ]
    total = 0.0
    for key, (tag, question) in meta.items():
        rec = load(f"{key}/run_record.json")
        cfg = rec["config"]
        jobs = cfg.get("n_jobs", "--")
        workers = cfg.get("workers", 1)
        if key == "e6":
            # Resumable campaign: the run record only times the final invocation.
            secs = sum(float(v) for v in
                       load("e6/raw/e6_summary.json")["timings_seconds"].values())
        else:
            secs = rec["duration_seconds"]
        mins = secs / 60.0
        total += mins
        out.append(fr"{tag} & {question} & {jobs} & {workers} & CPU & {mins:.1f} \\")

    out.append(r"\midrule")
    for key, tag, question, pattern, resumed in gpu:
        rec_path = RESULTS / key / "run_record.json"
        if not rec_path.exists():          # a stage that has not been run yet is simply absent
            continue
        rec = json.loads(rec_path.read_text(encoding="utf-8"))
        argv = rec.get("argv", [])
        workers = argv[argv.index("--workers") + 1] if "--workers" in argv else "--"
        device = argv[argv.index("--device") + 1].upper() if "--device" in argv else "CPU"
        models = 0
        for f in sorted((RESULTS / key / "raw").glob(pattern)):
            payload = json.loads(f.read_text(encoding="utf-8"))
            models += len(payload.get("diagnoses") or payload.get("runs") or [])
        mins = rec["duration_seconds"] / 60.0
        total += mins
        mark = r"$^{\dagger}$" if resumed else ""
        out.append(fr"{tag} & {question} & {models} & {workers} & {device} & {mins:.1f}{mark} \\")

    out += [r"\midrule", fr"\multicolumn{{5}}{{l}}{{total}} & {total:.1f} \\",
            r"\bottomrule", r"\end{tabular}"]
    write("tab_cost", out)


def main() -> None:
    print("Generating tables from raw results:")
    table_e1()
    table_e4()
    table_e5()
    table_e6()
    table_traceability()
    table_cost()
    print("done.")


if __name__ == "__main__":
    main()
