#!/usr/bin/env python3
"""Emit every number quoted in the manuscript as a LaTeX macro, read from raw results.

The manuscript never writes a measured number literally: it uses the macros defined in
``paper/generated/numbers.tex``, which this script regenerates from
``results/``. ``scripts/check_manuscript_numbers.py`` then verifies that the file on disk is
exactly what the results imply, and that every macro the text uses is defined.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict, List

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
RESULTS = REPO_ROOT / "results"
OUT = REPO_ROOT / "paper" / "generated" / "numbers.tex"


def load(rel: str) -> Any:
    path = RESULTS / rel
    if not path.exists():
        raise SystemExit(f"missing results file {path}; run the corresponding campaign first")
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


class Macros:
    """Accumulates ``\\newcommand`` definitions with LaTeX-safe names."""

    def __init__(self) -> None:
        self.items: List[tuple[str, str]] = []
        self.seen: set[str] = set()

    def add(self, name: str, value: str) -> None:
        if not name.isalpha():
            raise ValueError(f"macro name must be letters only, got {name!r}")
        if name in self.seen:
            raise ValueError(f"duplicate macro {name!r}")
        self.seen.add(name)
        self.items.append((name, value))

    def num(self, name: str, value: float, dec: int = 3) -> None:
        self.add(name, f"{value:.{dec}f}")

    def integer(self, name: str, value: int) -> None:
        self.add(name, f"{int(value):,}".replace(",", r"\,"))

    def render(self) -> str:
        head = ("% Generated by scripts/make_numbers.py from results/. Do not edit by hand.\n"
                "% Every measured quantity quoted in the manuscript is defined here.\n")
        body = "\n".join(fr"\newcommand{{\{n}}}{{{v}}}" for n, v in self.items)
        return head + body + "\n"


def _pct(x: float) -> str:
    return f"{100 * x:.1f}"


_DIGITS = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
           "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}


def word(n: float) -> str:
    """Spell a number digit by digit: LaTeX macro names may only contain letters.

    ``64 -> SixFour``, ``1024 -> OneZeroTwoFour``, ``0.4 -> ZeroPFour``.
    """
    s = f"{n:g}"
    return "".join("P" if c == "." else _DIGITS[c] for c in s)


def build() -> Macros:
    m = Macros()

    # ---------------- environment / cost ----------------
    durations: Dict[str, float] = {}
    words = {"e1": "Eone", "e2": "Etwo", "e3": "Ethree",
             "e4": "Efour", "e5": "Efive", "e6": "Esix"}
    for exp in ("e1", "e2", "e3", "e4", "e5", "e6"):
        if exp == "e6":
            # E6 is resumable, so its run record only times the final (skipping)
            # invocation. The real cost is the per-width compute recorded in the
            # raw files.
            durations[exp] = sum(float(v) for v in
                                 load("e6/raw/e6_summary.json")["timings_seconds"].values())
        else:
            durations[exp] = float(load(f"{exp}/run_record.json")["duration_seconds"])
        if exp == "e6":  # the only per-campaign duration quoted in prose
            m.num(f"Dur{words[exp]}Min", durations[exp] / 60.0, 1)
    m.num("DurTotalMin", sum(durations.values()) / 60.0, 1)
    env = load("e1/run_record.json")["environment"]
    m.add("EnvPython", env["python"])
    m.add("EnvNumpy", env["numpy"])
    m.add("EnvScipy", env["scipy"])
    m.add("EnvTorch", str(env["torch"]))
    m.integer("EnvCpuCount", int(env["cpu_count"]))

    # ---------------- E1 ----------------
    e1p = load("e1/raw/e1_rows.json")
    rows = e1p["rows"]
    m.integer("EoneMeasurements", e1p["n_measurements"])
    m.integer("EoneViolations", e1p["floor_violations"])
    m.integer("EoneConfigs", len(rows))
    m.integer("EoneTrials", rows[0]["trials"])
    tied = [r["tied_ratio_mean_sq_mean"] for r in rows]
    m.num("EoneTiedRatioMin", min(tied), 3)
    m.num("EoneTiedRatioMax", max(tied), 3)
    dmax = max(r["d"] for r in rows)
    rmax = max(r["ratio"] for r in rows)
    top = next(r for r in rows if r["d"] == dmax and r["ratio"] == rmax)
    m.integer("EoneTopD", dmax)
    m.integer("EoneTopF", top["F"])
    m.num("EoneTopTiedRatio", top["tied_ratio_mean_sq_mean"], 4)
    m.num("EoneTopPinvRatio", top["pinv_ratio_mean_sq_mean"], 4)
    # The largest single-trial ratio, not the largest per-config mean: "as large as" should
    # quote the extreme actually observed.
    m.add("EoneGaussianRatioMax",
          f"{max(r['gaussian_ratio_mean_sq_max'] for r in rows):.1e}")
    tf = [r["tight_frame_ratio_mean_sq"] for r in rows if r.get("tight_frame_ratio_mean_sq")]
    if tf:
        # Deviation from exact equality, not the ratio itself: the ratio prints as 1.000000
        # and would hide the fact that the agreement is at machine precision.
        m.add("EoneTightFrameDev", f"{max(abs(x - 1.0) for x in tf):.0e}")
        m.integer("EoneTightFrameConfigs", len(tf))

    # ---------------- E2 ----------------
    profs = load("e2/raw/e2_profiles.json")["profiles"]
    main = [p for p in profs if abs(p["theta"] - 0.5) < 1e-12]
    m.integer("EtwoTrials", main[0]["trials"])
    m.integer("EtwoThetaCount", len({p["theta"] for p in profs}))
    for p in sorted(main, key=lambda p: p["d"]):
        # Only the endpoints of the sweep are quoted in prose; Table 2 carries the rest.
        if p["d"] not in (min(q["d"] for q in main), max(q["d"] for q in main)):
            continue
        tag = "Etwo" + word(p["d"])
        m.integer(tag + "SNF", p["s95"])
        cert = p["separation_certificate"]
        if cert and p["d"] == max(q["d"] for q in main):
            m.num(tag + "LinRms", cert["linear_rms_error"], 4)
            m.num(tag + "LinRmsFloor", cert["linear_rms_floor"], 4)
            m.num(tag + "LinRmsOverRoot", cert["linear_rms_over_dminushalf"], 2)
    # threshold sensitivity (ablation A7) at the largest width
    dmax2 = max(p["d"] for p in main)
    for p in sorted([q for q in profs if q["d"] == dmax2], key=lambda q: q["theta"]):
        m.integer("EtwoTheta" + word(p["theta"]) + "SNF", p["s95"])
    m.integer("EtwoThetaDmax", dmax2)

    # ---------------- E3 ----------------
    e3 = load("e3/raw/e3_rows.json")
    s3 = e3["summary"]
    m.integer("EthreeConfigs", s3["n_configurations"])
    m.integer("EthreeViolations", s3["floor_violations"])
    m.num("EthreeRatioMin", s3["ratio_uniform_to_s_over_d_min"], 4)
    m.num("EthreeRatioMax", s3["ratio_uniform_to_s_over_d_max"], 4)
    mcs = e3["monte_carlo_checks"]
    m.num("EthreeMcMaxRelDiff", max(c["rel_diff"] for c in mcs), 4)
    m.integer("EthreeMcTrials", mcs[0]["mc_trials"])
    ru = [r["ratio_uniform_to_floor"] for r in e3["rows"]]
    m.num("EthreeUniformOverFloorMin", min(ru), 4)
    m.num("EthreeUniformOverFloorMax", max(ru), 4)

    # ---------------- E4 ----------------
    e4 = load("e4/raw/e4_runs.json")
    summ = e4["summary"]
    m.integer("EfourRuns", len(e4["runs"]))
    m.integer("EfourSteps", e4["runs"][0]["steps"])
    m.integer("EfourConfigs", len({(r["d"], r["F"]) for r in e4["runs"]}))
    for variant, tag in (("free", "Free"), ("tied", "Tied"), ("softmax", "Softmax")):
        s = summ[variant]
        m.integer(f"Efour{tag}Runs", s["n_runs"])
        m.num(f"Efour{tag}RatioMean", s["ratio_mean_sq_mean"], 4)
        m.num(f"Efour{tag}RatioMax", s["ratio_mean_sq_max"], 4)
        m.integer(f"Efour{tag}BelowFloor", s["n_below_floor"])
    m.num("EfourTiedFrameResidualMean", summ["tied"]["tight_frame_residual_mean"], 4)
    m.num("EfourTiedFrameResidualMax", summ["tied"]["tight_frame_residual_max"], 4)
    m.num("EfourSoftmaxRatioMaxMean", summ["softmax"]["ratio_max_mean"], 3)
    unc = summ["uncalibrated"]
    m.add("EfourUncalRawRatioMean", f"{unc['ratio_mean_sq_raw_mean']:.2e}"
          if unc["ratio_mean_sq_raw_mean"] > 0 else "0")
    m.add("EfourUncalGainMin", f"{unc['diag_gain_min_abs_min']:.2e}"
          if unc["diag_gain_min_abs_min"] > 0 else "0")
    m.integer("EfourUncalRuns", unc["n_runs"])
    m.integer("EfourUncalDegenerate", unc["n_degenerate"])
    m.integer("EfourUncalBelowFloor", unc["n_below_floor"])

    # ---------------- E5 ----------------
    e5 = load("e5/raw/e5_runs.json")
    runs = e5["runs"]
    primary = e5["primary_train_sparsity"]
    cfg = load("e5/run_record.json")["config"]
    m.integer("EfiveD", cfg["d"])
    m.integer("EfiveF", cfg["F"])
    m.integer("EfiveSeeds", cfg["n_seeds"])
    m.integer("EfiveSteps", cfg["steps"])
    m.integer("EfiveEvalTrials", cfg["eval_trials"])
    m.num("EfivePrimaryP", primary, 3)
    m.num("EfiveWelchFloor", runs[0]["welch_floor_mean_sq"], 5)

    sel = [r for r in runs if r["loss_kind"] == "random" or r["p_train"] == primary]

    def row_at(sub, s):
        return [next(x for x in r["rows"] if x["s"] == s) for r in sub]

    for kind, tag in (("L4", "Lfour"), ("L2", "Ltwo"), ("random", "Rand")):
        sub = [r for r in sel if r["loss_kind"] == kind]
        if not sub:
            continue
        for ro, rtag in (("ls", "Ls"), ("pinv", "Pinv"), ("wout", "Wout")):
            ratios = [r["floor_stats"][ro]["ratio_mean_sq"] for r in sub
                      if "ratio_mean_sq" in r["floor_stats"][ro]]
            # `wout` is the readout under which L4 loses to the random code; it is quoted for
            # L4 and random precisely so that unfavourable comparison appears in the text.
            # `wout` is not emitted for the random control: that control has no trained
            # decoder, so `random_code_baseline` sets W_out = pinv(Phi) and the column would
            # duplicate `Pinv` under a name that implies a trained decoder. Quoting it against
            # a trained model's W_out compares two different objects (audit finding P1).
            # `wout` for L2 is simply never quoted.
            if rtag == "Wout" and kind != "L4":
                continue
            if kind == "L4" or rtag in ("Ls", "Pinv"):
                m.num(f"Efive{tag}Ratio{rtag}Mean", float(np.mean(ratios)), 4)
            # Only the L4 pinv/ls ranges are quoted in prose.
            if kind == "L4" and rtag in ("Pinv", "Ls"):
                m.num(f"Efive{tag}Ratio{rtag}Min", float(np.min(ratios)), 4)
                m.num(f"Efive{tag}Ratio{rtag}Max", float(np.max(ratios)), 4)
        if kind == "L4":
            m.integer(f"Efive{tag}SmodelMax", int(np.max([r["s95_model"] for r in sub])))
        lin = [r["linearity"] for r in sub]
        if kind != "random":  # Table 5 carries the random-code control
            m.add(f"Efive{tag}NegPre",
                  _pct(float(np.mean([x["frac_relu_clipped"] for x in lin]))))
            m.add(f"Efive{tag}AgreeLinear",
                  _pct(float(np.mean([x["decision_agreement_with_linear"] for x in lin]))))
            m.num(f"Efive{tag}WoutPinvDist",
                  float(np.mean([x["rel_distance_wout_to_pinv"] for x in lin])), 3)
        mses = [r["final_mse"] for r in sub if r["final_mse"] is not None]
        if mses:
            m.add(f"Efive{tag}Mse", f"{float(np.mean(mses)):.2e}")

    # Where the separation is visible: recovery of the network output versus the best linear
    # readout of the same code, at each sparsity.
    l4 = [r for r in sel if r["loss_kind"] == "L4"]
    for s in (3, 4, 5, 6):
        rows = row_at(l4, s)
        tag = word(s)
        m.num(f"EfiveLfourPmodel{tag}", float(np.mean([x["p_rec_model"] for x in rows])), 3)
        if s != 3:  # at s = 3 both criteria are exact; the prose says so in words
            m.num(f"EfiveLfourPlin{tag}",
                  float(np.mean([max(x[f"p_rec_linear_{ro}"] for ro in ("pinv", "wout", "ls"))
                                 for x in rows])), 3)
        else:
            m.num(f"EfiveLfourRms{tag}",
                  float(np.mean([min(x[f"linear_rms_{ro}"] for ro in ("pinv", "wout", "ls"))
                                 for x in rows])), 4)
            m.num(f"EfiveLfourFloor{tag}", float(rows[0]["rms_floor_uniform"]), 4)
    # The best linear readout's own s95, which beats the network's -- reported, not hidden.
    m.integer("EfiveLfourSlinBestMax",
              int(np.max([max(r[f"s95_linear_{ro}"] for ro in ("pinv", "wout", "ls"))
                          for r in l4])))
    # At the secondary training sparsity the lead is not unanimous: count the seeds on which
    # the best linear readout strictly beats the network, rather than asserting all of them.
    l4_sec = [r for r in runs
              if r["loss_kind"] == "L4" and r.get("p_train") not in (None, primary)]
    if l4_sec:
        ahead = sum(1 for r in l4_sec
                    if max(r[f"s95_linear_{ro}"] for ro in ("pinv", "wout", "ls"))
                    > r["s95_model"])
        m.integer("EfiveLfourSlinAheadSecondary", ahead)

    l2 = [r for r in sel if r["loss_kind"] == "L2"]
    m.num("EfiveLtwoPmodelOne", float(np.mean([x["p_rec_model"] for x in row_at(l2, 1)])), 3)
    rnd = [r for r in sel if r["loss_kind"] == "random"]
    m.num("EfiveRandPlinThree",
          float(np.mean([x["p_rec_linear_ls"] for x in row_at(rnd, 3)])), 3)

    # Ablation A5: the secondary training sparsity, as a replication check.
    secondary = sorted({r["p_train"] for r in runs
                        if r["loss_kind"] != "random"} - {primary})
    if secondary:
        p2 = secondary[0]
        m.num("EfiveSecondaryP", p2, 3)
        for kind, tag in (("L4", "Lfour"), ("L2", "Ltwo")):
            sub2 = [r for r in runs if r["loss_kind"] == kind and r["p_train"] == p2]
            if not sub2:
                continue
            m.num(f"Efive{tag}SecRatioLsMean",
                  float(np.mean([r["floor_stats"]["ls"]["ratio_mean_sq"] for r in sub2
                                 if "ratio_mean_sq" in r["floor_stats"]["ls"]])), 4)
            m.add(f"Efive{tag}SecAgreeLinear",
                  _pct(float(np.mean([r["linearity"]["decision_agreement_with_linear"]
                                      for r in sub2]))))

    cmp_ls = e5["comparisons"]["ls"]
    # Every pairwise test returns the same saturated p; the text quotes it once and explains
    # why, so only that one macro is emitted.
    if "L4_vs_L2" in cmp_ls:
        m.add("EfiveMwPLfourLtwo", f"{cmp_ls['L4_vs_L2']['p_value']:.4f}")

    # ---------------- E6 ----------------
    e6 = load("e6/raw/e6_summary.json")
    per_d = sorted(e6["per_d"], key=lambda e: e["d"])
    m.integer("EsixDmax", per_d[-1]["d"])
    m.integer("EsixFmax", per_d[-1]["F"])
    for e in per_d:
        # Table 6 carries every width; prose quotes only the two endpoints.
        if e is not per_d[0] and e is not per_d[-1]:
            continue
        tag = "Esix" + word(e["d"])
        m.integer(tag + "SNF", e["s95"])
        if e is per_d[-1]:
            m.integer(tag + "Trials", e["trials"])
            # The d/(16 ln d) reference value is no longer quoted: decision D7 withdrew the
            # curve, its constant being inherited rather than derived here.
            m.num(tag + "DurationMin", e["duration_seconds"] / 60.0, 1)
    if e6["fit"]:
        # The grid fit is superseded by the interpolated one below; only the point count is
        # quoted from it.
        m.integer("EsixFitPoints", e6["fit"]["n_points"])

    # The grid statistic floors the crossing, and it floors hardest where the grid is coarse
    # relative to the transition (small d) -- which bends the apparent growth upward. Report
    # the interpolated crossing alongside it, and the competing one-parameter shapes, so the
    # reader can see how little four points discriminate.
    sys.path.insert(0, str(REPO_ROOT / "src"))
    from lrtr.stats import wilson_interval  # noqa: E402
    from lrtr.threshold import s95_interpolated  # noqa: E402

    ds = [e["d"] for e in per_d]
    interp = [s95_interpolated([r["s"] for r in e["rows"]], [r["p_rec"] for r in e["rows"]])
              for e in per_d]
    m.num("EsixInterp" + word(per_d[0]["d"]), interp[0], 2)
    x = np.array(ds, dtype=float)
    y = np.array(interp, dtype=float)
    shapes = {"Log": x / np.log(x), "Lin": x, "LogSq": x / np.log(x) ** 2}
    for tag, xx in shapes.items():
        c = float((xx @ y) / (xx @ xx))
        r2 = 1.0 - float(((y - c * xx) ** 2).sum()) / float(((y - y.mean()) ** 2).sum())
        m.num(f"EsixInterpRsq{tag}", r2, 4)
    m.num("EsixInterpC", float((shapes["Log"] @ y) / (shapes["Log"] @ shapes["Log"])), 4)
    m.num("EsixGrowthGrid", per_d[-1]["s95"] / per_d[0]["s95"], 2)
    m.num("EsixGrowthInterp", interp[-1] / interp[0], 2)
    m.num("EsixGrowthPredicted",
          float((ds[-1] / np.log(ds[-1])) / (ds[0] / np.log(ds[0]))), 2)

    # Trial budget vs the confidence the point estimate can support at the largest width.
    top = per_d[-1]
    m.num("EsixTopBestWilsonLow", wilson_interval(top["trials"], top["trials"])[0], 3)
    m.integer("EsixEnergyTrialsTop", top["n_energy_trials"])

    # ---------------- G1: geometry versus readout suboptimality ----------------
    # The published attainment ratio factors exactly as R_geom x R_readout. Under the
    # calibrated pseudoinverse R_readout is 1 by construction, so the ratio the manuscript
    # used to quote is R_geom alone -- a property of the code, not of the decoder.
    tags = {"L4": "Lfour", "L2": "Ltwo", "random": "Rand"}
    for c in load("g1/g1_reanalysis.json")["cells"]:
        if c["p_train"] != 0.01:          # the primary cell; p=0.02 is the robustness check
            continue
        t = "Gone" + tags[c["loss_kind"]]
        m.num(t + "Ratio", c["ratio_vs_welch_pinv"], 4)
        m.num(t + "Rgeom", c["R_geom"], 4)
        m.num(t + "RreadoutPinv", c["R_readout_pinv"], 6)
        m.num(t + "RreadoutWout", c["R_readout_wout"], 4)
        m.num(t + "LeverageMin", c["leverage_min"], 4)
        m.num(t + "LeverageMax", c["leverage_max"], 4)
        m.num(t + "LeverageCv", c["leverage_cv"], 4)
    # The L2 geometry gap grows with the training sparsity, which is worth one number.
    hi = [c for c in load("g1/g1_reanalysis.json")["cells"]
          if c["loss_kind"] == "L2" and c["p_train"] == 0.02][0]
    m.num("GoneLtwoRgeomDenseP", hi["R_geom"], 4)

    # ---------------- Stage A of the accelerator campaign, and its re-analyses ----------------
    # Only what Section 10.5 quotes. check_manuscript_numbers.py requires every generated macro to
    # be used, which is the right constraint: it stops the file accumulating numbers nobody reads.
    W = {50: "Fifty", 100: "Hundred", 200: "TwoHundred"}
    LO = {"L4": "Lfour", "L2": "Ltwo", "random": "Rand"}
    per_width = load("e7/raw/e7_stage_A.json")["report"]["per_width"]
    for d, tag in W.items():
        for loss, lt in LO.items():                      # the geometry table: all nine cells
            m.num(f"SA{lt}{tag}Rgeom", per_width[str(d)][loss]["R_geom"], 4)
    m.num("SALfourFiftyRreadout", per_width["50"]["L4"]["R_readout_wout"], 4)

    prim = {(c["loss"], c["d"]): c for c in
            load("e7/derived/primary_comparison.json")["cells"]}
    for d, tag in W.items():
        for loss in ("L4", "L2"):                        # the primary table: trained cells only
            v = prim[(loss, d)]["network_minus_probe"]["post_relu"]["s95"]
            t = f"Prim{LO[loss]}{tag}Post"
            m.num(t + "Diff", v["mean"], 2)
            m.num(t + "CiLow", v["ci_low"], 2)
            m.num(t + "CiHigh", v["ci_high"], 2)
            m.integer(t + "Ties", v["n_zero"])
            m.integer(t + "ProbeWins", v["n_negative"])
    # The second pre-registered estimand. D17 decided to report both because they disagree; only
    # `s95` reached the manuscript, so these close that gap. The direction of the AUC difference
    # itself depends on the width, which is why all three widths get macros rather than a summary.
    m.integer("EsevenSeeds", prim[("L4", 200)]["n_seeds"])
    for d, tag in W.items():
        v = prim[("L4", d)]["network_minus_probe"]["post_relu"]["auc"]
        t = f"Auc{tag}"
        m.num(t + "Diff", v["mean"], 4)
        m.num(t + "CiLow", v["ci_low"], 4)
        m.num(t + "CiHigh", v["ci_high"], 4)
        # Only the winning side's count, since the cells are unanimous and the loser's count is 0.
        # Emitting both would leave a macro nobody reads, which the number check rightly rejects.
        if v["mean"] > 0:
            m.integer(t + "NetWins", v["n_positive"])
        else:
            m.integer(t + "ProbeWins", v["n_negative"])

    pre50 = prim[("L4", 50)]["network_minus_probe"]["pre_relu"]["s95"]
    pre200 = prim[("L4", 200)]["network_minus_probe"]["pre_relu"]["s95"]
    m.num("PrimLfourFiftyPreDiff", pre50["mean"], 2)
    m.integer("PrimLfourFiftyPreProbeWins", pre50["n_negative"])
    m.num("PrimLfourTwoHundredPreDiff", pre200["mean"], 2)

    full = {(c["loss"], c["d"]): c for c in
            load("e7/derived/all_feature_frontier.json")["cells"]}
    for d, tag in W.items():
        for loss, lt in LO.items():                      # the frontier table: all nine cells
            m.num(f"Full{lt}{tag}KappaMin", full[(loss, d)]["kappa_min_full_mean"], 4)
    hi200 = full[("L4", 200)]
    m.num("FullLfourTwoHundredSubsetOver", hi200["subset_overestimate_mean"], 4)
    m.integer("FullLfourTwoHundredArgminFound", hi200["models_where_subset_found_the_argmin"])
    m.integer("FullLfourTwoHundredArgminRankMed",
              int(hi200["leverage_rank_of_true_argmin_median"]))

    # ---------------- E8: which half of the training does the work ----------------
    import collections

    e8 = collections.defaultdict(list)
    # d=200 was run separately, after the audit asked for the third width, so it has its own run
    # record and its own provenance. Both are read; neither is merged on disk.
    for rel in ("e8/raw/e8_runs.json", "e8_d200/raw/e8_runs.json"):
        for r in load(rel)["runs"]:
            e8[(r["arm"], r["d"])].append(r)
    ARM = {"trained": "Trained", "frozen": "Frozen", "random": "Random"}
    for (arm, dd), rs in e8.items():
        if dd not in W:
            continue
        t = f"Eeight{ARM[arm]}{W[dd]}"
        m.num(t + "Rgeom", float(np.mean([x["theory"]["analog"]["R_geom"] for x in rs])), 4)
        m.num(t + "Kappa", float(np.mean([x["theory"]["affine"]["kappa_min"] for x in rs])), 3)
        ro = [x["theory"]["analog"]["R_readout"].get("wout") for x in rs]
        ro = [v for v in ro if v is not None]
        if ro:
            m.num(t + "Rreadout", float(np.mean(ro)), 4)
    m.integer("EeightSeeds", len(e8[("trained", 50)]))

    # ---------------- Stage C: the fourth width, and what it costs us ----------------
    # Every quantity here is derived from the exact all-feature frontier, never the subset, because
    # the subset's error is asymmetric between the arms and grows with width -- see D20. The fits and
    # the crossing are computed here rather than typed, so they move if the data moves.
    scr = load("e7_stageC/raw/e7_stage_C.json")["report"]["per_width"]["400"]
    afA = {(c["loss"], c["d"]): c for c in load("e7/derived/all_feature_frontier.json")["cells"]}
    afC = {(c["loss"], c["d"]): c for c in
           load("e7_stageC/derived/all_feature_frontier.json")["cells"]}
    af = {**afA, **afC}
    WIDTHS4 = (50, 100, 200, 400)

    def kap(loss: str, d: int) -> np.ndarray:
        return np.array([x["kappa_min_full"] for x in af[(loss, d)]["per_model"]], float)

    m.integer("ScSeeds", af[("L4", 400)]["n_models"])
    # The optimisation budget is fixed across widths, which is one candidate explanation for the
    # trained arm's decelerating exponent, so the number belongs in the text that raises it.
    m.integer("EsevenSteps", load("e7_stageC/run_record.json")["config"]["steps"])
    for loss, lt in (("L4", "Lfour"), ("L2", "Ltwo"), ("random", "Rand")):
        m.num(f"Sc{lt}Kappa", float(kap(loss, 400).mean()), 4)
        m.num(f"Sc{lt}Rgeom", scr[loss]["R_geom"], 4)

    # The out-of-sample test. Two numbers, and the difference between them matters.
    #
    # REGISTERED is what `configs/e7_stageC.json` committed to before the width was run. It came
    # from the subset frontier, the only statistic available at the time. It is a historical
    # constant, not a measurement, so it is written here rather than derived -- deriving it would
    # let it drift when the data does, which is the opposite of what a pre-registration is for.
    #
    # The refit below is on exact values, and it is the honest thing to report *alongside*, never
    # instead: it was computed after seeing the measurement, and it happens to give a smaller error.
    # An earlier version of this file emitted only the refit and the manuscript called it "the
    # number we registered", which it was not.
    SC_REGISTERED = 10.79
    m.num("ScRegistered", SC_REGISTERED, 2)
    meas = float(kap("L4", 400).mean())
    m.num("ScMeasured", meas, 3)
    m.num("ScRegisteredErrorPct", 100.0 * (meas - SC_REGISTERED) / SC_REGISTERED, 2)

    lo = np.polyfit(np.log([50, 100, 200]), np.log([kap("L4", d).mean() for d in (50, 100, 200)]), 1)
    pred = float(np.exp(lo[1] + lo[0] * np.log(400)))
    m.num("ScFitExponent", float(lo[0]), 4)
    m.num("ScPredicted", pred, 3)
    m.num("ScPredErrorPct", 100.0 * (meas - pred) / pred, 2)

    # Trained against untrained, at all four widths, with the margin summarised both ways.
    for d in WIDTHS4:
        t, r = kap("L4", d), kap("random", d)
        tag = {50: "Fifty", 100: "Hundred", 200: "TwoHundred", 400: "FourHundred"}[d]
        m.num(f"Margin{tag}Gap", float(t.mean() - r.mean()), 4)
        m.num(f"Margin{tag}Ratio", float(t.mean() / r.mean()), 4)
    rng = np.random.default_rng(0)

    def boot_gap(d: int, reps: int = 40_000) -> np.ndarray:
        t, r = kap("L4", d), kap("random", d)
        return (t[rng.integers(0, len(t), (reps, len(t)))].mean(1)
                - r[rng.integers(0, len(r), (reps, len(r)))].mean(1))

    drop = boot_gap(200) - boot_gap(400)
    m.num("MarginDrop", float(np.mean(drop)), 4)
    m.num("MarginDropCiLow", float(np.quantile(drop, 0.025)), 4)
    m.num("MarginDropCiHigh", float(np.quantile(drop, 0.975)), 4)

    x4 = np.log(WIDTHS4)
    ft = np.polyfit(x4, np.log([kap("L4", d).mean() for d in WIDTHS4]), 1)
    fr = np.polyfit(x4, np.log([kap("random", d).mean() for d in WIDTHS4]), 1)
    m.num("ScExpTrained", float(ft[0]), 4)
    m.num("ScExpRandom", float(fr[0]), 4)
    m.integer("ScCrossing", int(round(np.exp((ft[1] - fr[1]) / (fr[0] - ft[0])))))

    # The shortcut's justification, and how fast it decays.
    for d in WIDTHS4:
        c = af[("L4", d)]
        tag = {50: "Fifty", 100: "Hundred", 200: "TwoHundred", 400: "FourHundred"}[d]
        m.num(f"Subset{tag}Over", c["subset_overestimate_mean"], 4)
        m.integer(f"Subset{tag}Rank", int(c["leverage_rank_of_true_argmin_median"]))
    m.integer("SubsetFourHundredFound", af[("L4", 400)]["models_where_subset_found_the_argmin"])

    # The matched comparison at the fourth width.
    pc = {(c["loss"], c["d"]): c for c in
          load("e7_stageC/derived/primary_comparison.json")["cells"]}
    v = pc[("L4", 400)]["network_minus_probe"]["post_relu"]["s95"]
    m.num("ScPrimDiff", v["mean"], 2)
    m.integer("ScPrimProbeWins", v["n_negative"])

    # Whether the cross-talk the frozen arm gives up is bought or lost: its own objective, its own
    # representation, against the readout that attains the code-specific cross-talk optimum.
    # Only the cells the manuscript cites are emitted; all nine are in the derived JSON. The
    # untrained arm appears once, as the scoring check -- its readout *is* pinv, so its ratio must
    # come back at 1, and a macro says so with the same provenance as the rest.
    for c in load("e8/derived/frozen_readout_tradeoff.json")["cells"]:
        if c["d"] not in W or (c["arm"] == "random" and c["d"] != 200):
            continue
        t = f"Eeight{ARM[c['arm']]}{W[c['d']]}"
        m.num(t + "TaskGain", c["task_gain_over_pinv"], 2)
        if (c["arm"], c["d"]) == ("frozen", 200):
            m.integer(t + "TaskWins", c["models_where_wout_wins"])
    return m


def main() -> None:
    m = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(m.render(), encoding="utf-8")
    print(f"wrote {len(m.items)} macros to {OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
