#!/usr/bin/env python3
"""Emit every number quoted in the manuscript as a LaTeX macro, read from raw results.

The manuscript never writes a measured number literally: it uses the macros defined in
``paper/generated/numbers.tex``, which this script regenerates from
``results/``. ``scripts/check_manuscript_numbers.py`` then verifies that the file on disk is
exactly what the results imply, and that every macro the text uses is defined.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict, List

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
RESULTS = REPO_ROOT / "results"
OUT = REPO_ROOT / "paper" / "generated" / "numbers.tex"


def load(rel: str) -> Any:
    path = RESULTS / rel
    if not path.exists():
        raise SystemExit(f"missing results file {path}; run the corresponding campaign first")
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


class Macros:
    """Accumulates ``\\newcommand`` definitions with LaTeX-safe names."""

    def __init__(self) -> None:
        self.items: List[tuple[str, str]] = []
        self.seen: set[str] = set()

    def add(self, name: str, value: str) -> None:
        if not name.isalpha():
            raise ValueError(f"macro name must be letters only, got {name!r}")
        if name in self.seen:
            raise ValueError(f"duplicate macro {name!r}")
        self.seen.add(name)
        self.items.append((name, value))

    def num(self, name: str, value: float, dec: int = 3) -> None:
        self.add(name, f"{value:.{dec}f}")

    def integer(self, name: str, value: int) -> None:
        self.add(name, f"{int(value):,}".replace(",", r"\,"))

    def render(self) -> str:
        head = ("% Generated by scripts/make_numbers.py from results/. Do not edit by hand.\n"
                "% Every measured quantity quoted in the manuscript is defined here.\n")
        body = "\n".join(fr"\newcommand{{\{n}}}{{{v}}}" for n, v in self.items)
        return head + body + "\n"


def _pct(x: float) -> str:
    return f"{100 * x:.1f}"


_DIGITS = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
           "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}


def word(n: float) -> str:
    """Spell a number digit by digit: LaTeX macro names may only contain letters.

    ``64 -> SixFour``, ``1024 -> OneZeroTwoFour``, ``0.4 -> ZeroPFour``.
    """
    s = f"{n:g}"
    return "".join("P" if c == "." else _DIGITS[c] for c in s)


def build() -> Macros:
    m = Macros()

    # ---------------- environment / cost ----------------
    durations: Dict[str, float] = {}
    words = {"e1": "Eone", "e2": "Etwo", "e3": "Ethree",
             "e4": "Efour", "e5": "Efive", "e6": "Esix"}
    for exp in ("e1", "e2", "e3", "e4", "e5", "e6"):
        if exp == "e6":
            # E6 is resumable, so its run record only times the final (skipping)
            # invocation. The real cost is the per-width compute recorded in the
            # raw files.
            durations[exp] = sum(float(v) for v in
                                 load("e6/raw/e6_summary.json")["timings_seconds"].values())
        else:
            durations[exp] = float(load(f"{exp}/run_record.json")["duration_seconds"])
        if exp == "e6":  # the only per-campaign duration quoted in prose
            m.num(f"Dur{words[exp]}Min", durations[exp] / 60.0, 1)
    m.num("DurTotalMin", sum(durations.values()) / 60.0, 1)
    env = load("e1/run_record.json")["environment"]
    m.add("EnvPython", env["python"])
    m.add("EnvNumpy", env["numpy"])
    m.add("EnvScipy", env["scipy"])
    m.add("EnvTorch", str(env["torch"]))
    m.integer("EnvCpuCount", int(env["cpu_count"]))

    # ---------------- E1 ----------------
    e1p = load("e1/raw/e1_rows.json")
    rows = e1p["rows"]
    m.integer("EoneMeasurements", e1p["n_measurements"])
    m.integer("EoneViolations", e1p["floor_violations"])
    m.integer("EoneConfigs", len(rows))
    m.integer("EoneTrials", rows[0]["trials"])
    tied = [r["tied_ratio_mean_sq_mean"] for r in rows]
    m.num("EoneTiedRatioMin", min(tied), 3)
    m.num("EoneTiedRatioMax", max(tied), 3)
    dmax = max(r["d"] for r in rows)
    rmax = max(r["ratio"] for r in rows)
    top = next(r for r in rows if r["d"] == dmax and r["ratio"] == rmax)
    m.integer("EoneTopD", dmax)
    m.integer("EoneTopF", top["F"])
    m.num("EoneTopTiedRatio", top["tied_ratio_mean_sq_mean"], 4)
    m.num("EoneTopPinvRatio", top["pinv_ratio_mean_sq_mean"], 4)
    # The largest single-trial ratio, not the largest per-config mean: "as large as" should
    # quote the extreme actually observed.
    m.add("EoneGaussianRatioMax",
          f"{max(r['gaussian_ratio_mean_sq_max'] for r in rows):.1e}")
    tf = [r["tight_frame_ratio_mean_sq"] for r in rows if r.get("tight_frame_ratio_mean_sq")]
    if tf:
        # Deviation from exact equality, not the ratio itself: the ratio prints as 1.000000
        # and would hide the fact that the agreement is at machine precision.
        m.add("EoneTightFrameDev", f"{max(abs(x - 1.0) for x in tf):.0e}")
        m.integer("EoneTightFrameConfigs", len(tf))

    # ---------------- E2 ----------------
    profs = load("e2/raw/e2_profiles.json")["profiles"]
    main = [p for p in profs if abs(p["theta"] - 0.5) < 1e-12]
    m.integer("EtwoTrials", main[0]["trials"])
    m.integer("EtwoThetaCount", len({p["theta"] for p in profs}))
    for p in sorted(main, key=lambda p: p["d"]):
        # Only the endpoints of the sweep are quoted in prose; Table 2 carries the rest.
        if p["d"] not in (min(q["d"] for q in main), max(q["d"] for q in main)):
            continue
        tag = "Etwo" + word(p["d"])
        m.integer(tag + "SNF", p["s95"])
        cert = p["separation_certificate"]
        if cert and p["d"] == max(q["d"] for q in main):
            m.num(tag + "LinRms", cert["linear_rms_error"], 4)
            m.num(tag + "LinRmsFloor", cert["linear_rms_floor"], 4)
            m.num(tag + "LinRmsOverRoot", cert["linear_rms_over_dminushalf"], 2)
    # threshold sensitivity (ablation A7) at the largest width
    dmax2 = max(p["d"] for p in main)
    for p in sorted([q for q in profs if q["d"] == dmax2], key=lambda q: q["theta"]):
        m.integer("EtwoTheta" + word(p["theta"]) + "SNF", p["s95"])
    m.integer("EtwoThetaDmax", dmax2)

    # ---------------- E3 ----------------
    e3 = load("e3/raw/e3_rows.json")
    s3 = e3["summary"]
    m.integer("EthreeConfigs", s3["n_configurations"])
    m.integer("EthreeViolations", s3["floor_violations"])
    m.num("EthreeRatioMin", s3["ratio_uniform_to_s_over_d_min"], 4)
    m.num("EthreeRatioMax", s3["ratio_uniform_to_s_over_d_max"], 4)
    mcs = e3["monte_carlo_checks"]
    m.num("EthreeMcMaxRelDiff", max(c["rel_diff"] for c in mcs), 4)
    m.integer("EthreeMcTrials", mcs[0]["mc_trials"])
    ru = [r["ratio_uniform_to_floor"] for r in e3["rows"]]
    m.num("EthreeUniformOverFloorMin", min(ru), 4)
    m.num("EthreeUniformOverFloorMax", max(ru), 4)

    # ---------------- E4 ----------------
    e4 = load("e4/raw/e4_runs.json")
    summ = e4["summary"]
    m.integer("EfourRuns", len(e4["runs"]))
    m.integer("EfourSteps", e4["runs"][0]["steps"])
    m.integer("EfourConfigs", len({(r["d"], r["F"]) for r in e4["runs"]}))
    for variant, tag in (("free", "Free"), ("tied", "Tied"), ("softmax", "Softmax")):
        s = summ[variant]
        m.integer(f"Efour{tag}Runs", s["n_runs"])
        m.num(f"Efour{tag}RatioMean", s["ratio_mean_sq_mean"], 4)
        m.num(f"Efour{tag}RatioMax", s["ratio_mean_sq_max"], 4)
        m.integer(f"Efour{tag}BelowFloor", s["n_below_floor"])
    m.num("EfourTiedFrameResidualMean", summ["tied"]["tight_frame_residual_mean"], 4)
    m.num("EfourTiedFrameResidualMax", summ["tied"]["tight_frame_residual_max"], 4)
    m.num("EfourSoftmaxRatioMaxMean", summ["softmax"]["ratio_max_mean"], 3)
    unc = summ["uncalibrated"]
    m.add("EfourUncalRawRatioMean", f"{unc['ratio_mean_sq_raw_mean']:.2e}"
          if unc["ratio_mean_sq_raw_mean"] > 0 else "0")
    m.add("EfourUncalGainMin", f"{unc['diag_gain_min_abs_min']:.2e}"
          if unc["diag_gain_min_abs_min"] > 0 else "0")
    m.integer("EfourUncalRuns", unc["n_runs"])
    m.integer("EfourUncalDegenerate", unc["n_degenerate"])
    m.integer("EfourUncalBelowFloor", unc["n_below_floor"])

    # ---------------- E5 ----------------
    e5 = load("e5/raw/e5_runs.json")
    runs = e5["runs"]
    primary = e5["primary_train_sparsity"]
    cfg = load("e5/run_record.json")["config"]
    m.integer("EfiveD", cfg["d"])
    m.integer("EfiveF", cfg["F"])
    m.integer("EfiveSeeds", cfg["n_seeds"])
    m.integer("EfiveSteps", cfg["steps"])
    m.integer("EfiveEvalTrials", cfg["eval_trials"])
    m.num("EfivePrimaryP", primary, 3)
    m.num("EfiveWelchFloor", runs[0]["welch_floor_mean_sq"], 5)

    sel = [r for r in runs if r["loss_kind"] == "random" or r["p_train"] == primary]

    def row_at(sub, s):
        return [next(x for x in r["rows"] if x["s"] == s) for r in sub]

    for kind, tag in (("L4", "Lfour"), ("L2", "Ltwo"), ("random", "Rand")):
        sub = [r for r in sel if r["loss_kind"] == kind]
        if not sub:
            continue
        for ro, rtag in (("ls", "Ls"), ("pinv", "Pinv"), ("wout", "Wout")):
            ratios = [r["floor_stats"][ro]["ratio_mean_sq"] for r in sub
                      if "ratio_mean_sq" in r["floor_stats"][ro]]
            # `wout` is the readout under which L4 loses to the random code; it is quoted for
            # L4 and random precisely so that unfavourable comparison appears in the text.
            # `wout` is not emitted for the random control: that control has no trained
            # decoder, so `random_code_baseline` sets W_out = pinv(Phi) and the column would
            # duplicate `Pinv` under a name that implies a trained decoder. Quoting it against
            # a trained model's W_out compares two different objects (audit finding P1).
            # `wout` for L2 is simply never quoted.
            if rtag == "Wout" and kind != "L4":
                continue
            if kind == "L4" or rtag in ("Ls", "Pinv"):
                m.num(f"Efive{tag}Ratio{rtag}Mean", float(np.mean(ratios)), 4)
            # Only the L4 pinv/ls ranges are quoted in prose.
            if kind == "L4" and rtag in ("Pinv", "Ls"):
                m.num(f"Efive{tag}Ratio{rtag}Min", float(np.min(ratios)), 4)
                m.num(f"Efive{tag}Ratio{rtag}Max", float(np.max(ratios)), 4)
        if kind == "L4":
            m.integer(f"Efive{tag}SmodelMax", int(np.max([r["s95_model"] for r in sub])))
        lin = [r["linearity"] for r in sub]
        if kind != "random":  # Table 5 carries the random-code control
            m.add(f"Efive{tag}NegPre",
                  _pct(float(np.mean([x["frac_relu_clipped"] for x in lin]))))
            m.add(f"Efive{tag}AgreeLinear",
                  _pct(float(np.mean([x["decision_agreement_with_linear"] for x in lin]))))
            m.num(f"Efive{tag}WoutPinvDist",
                  float(np.mean([x["rel_distance_wout_to_pinv"] for x in lin])), 3)
        mses = [r["final_mse"] for r in sub if r["final_mse"] is not None]
        if mses:
            m.add(f"Efive{tag}Mse", f"{float(np.mean(mses)):.2e}")

    # Where the separation is visible: recovery of the network output versus the best linear
    # readout of the same code, at each sparsity.
    l4 = [r for r in sel if r["loss_kind"] == "L4"]
    for s in (3, 4, 5, 6):
        rows = row_at(l4, s)
        tag = word(s)
        m.num(f"EfiveLfourPmodel{tag}", float(np.mean([x["p_rec_model"] for x in rows])), 3)
        if s != 3:  # at s = 3 both criteria are exact; the prose says so in words
            m.num(f"EfiveLfourPlin{tag}",
                  float(np.mean([max(x[f"p_rec_linear_{ro}"] for ro in ("pinv", "wout", "ls"))
                                 for x in rows])), 3)
        else:
            m.num(f"EfiveLfourRms{tag}",
                  float(np.mean([min(x[f"linear_rms_{ro}"] for ro in ("pinv", "wout", "ls"))
                                 for x in rows])), 4)
            m.num(f"EfiveLfourFloor{tag}", float(rows[0]["rms_floor_uniform"]), 4)
    # The best linear readout's own s95, which beats the network's -- reported, not hidden.
    m.integer("EfiveLfourSlinBestMax",
              int(np.max([max(r[f"s95_linear_{ro}"] for ro in ("pinv", "wout", "ls"))
                          for r in l4])))
    # At the secondary training sparsity the lead is not unanimous: count the seeds on which
    # the best linear readout strictly beats the network, rather than asserting all of them.
    l4_sec = [r for r in runs
              if r["loss_kind"] == "L4" and r.get("p_train") not in (None, primary)]
    if l4_sec:
        ahead = sum(1 for r in l4_sec
                    if max(r[f"s95_linear_{ro}"] for ro in ("pinv", "wout", "ls"))
                    > r["s95_model"])
        m.integer("EfiveLfourSlinAheadSecondary", ahead)

    l2 = [r for r in sel if r["loss_kind"] == "L2"]
    m.num("EfiveLtwoPmodelOne", float(np.mean([x["p_rec_model"] for x in row_at(l2, 1)])), 3)
    rnd = [r for r in sel if r["loss_kind"] == "random"]
    m.num("EfiveRandPlinThree",
          float(np.mean([x["p_rec_linear_ls"] for x in row_at(rnd, 3)])), 3)

    # Ablation A5: the secondary training sparsity, as a replication check.
    secondary = sorted({r["p_train"] for r in runs
                        if r["loss_kind"] != "random"} - {primary})
    if secondary:
        p2 = secondary[0]
        m.num("EfiveSecondaryP", p2, 3)
        for kind, tag in (("L4", "Lfour"), ("L2", "Ltwo")):
            sub2 = [r for r in runs if r["loss_kind"] == kind and r["p_train"] == p2]
            if not sub2:
                continue
            m.num(f"Efive{tag}SecRatioLsMean",
                  float(np.mean([r["floor_stats"]["ls"]["ratio_mean_sq"] for r in sub2
                                 if "ratio_mean_sq" in r["floor_stats"]["ls"]])), 4)
            m.add(f"Efive{tag}SecAgreeLinear",
                  _pct(float(np.mean([r["linearity"]["decision_agreement_with_linear"]
                                      for r in sub2]))))

    cmp_ls = e5["comparisons"]["ls"]
    # Every pairwise test returns the same saturated p; the text quotes it once and explains
    # why, so only that one macro is emitted.
    if "L4_vs_L2" in cmp_ls:
        m.add("EfiveMwPLfourLtwo", f"{cmp_ls['L4_vs_L2']['p_value']:.4f}")

    # ---------------- E6 ----------------
    e6 = load("e6/raw/e6_summary.json")
    per_d = sorted(e6["per_d"], key=lambda e: e["d"])
    m.integer("EsixDmax", per_d[-1]["d"])
    m.integer("EsixFmax", per_d[-1]["F"])
    for e in per_d:
        # Table 6 carries every width; prose quotes only the two endpoints.
        if e is not per_d[0] and e is not per_d[-1]:
            continue
        tag = "Esix" + word(e["d"])
        m.integer(tag + "SNF", e["s95"])
        if e is per_d[-1]:
            m.integer(tag + "Trials", e["trials"])
            m.num(tag + "Reference", e["reference_union_bound"], 2)
            m.num(tag + "DurationMin", e["duration_seconds"] / 60.0, 1)
    if e6["fit"]:
        # The grid fit is superseded by the interpolated one below; only the point count is
        # quoted from it.
        m.integer("EsixFitPoints", e6["fit"]["n_points"])

    # The grid statistic floors the crossing, and it floors hardest where the grid is coarse
    # relative to the transition (small d) -- which bends the apparent growth upward. Report
    # the interpolated crossing alongside it, and the competing one-parameter shapes, so the
    # reader can see how little four points discriminate.
    sys.path.insert(0, str(REPO_ROOT / "src"))
    from lrtr.stats import wilson_interval  # noqa: E402
    from lrtr.threshold import s95_interpolated  # noqa: E402

    ds = [e["d"] for e in per_d]
    interp = [s95_interpolated([r["s"] for r in e["rows"]], [r["p_rec"] for r in e["rows"]])
              for e in per_d]
    m.num("EsixInterp" + word(per_d[0]["d"]), interp[0], 2)
    x = np.array(ds, dtype=float)
    y = np.array(interp, dtype=float)
    shapes = {"Log": x / np.log(x), "Lin": x, "LogSq": x / np.log(x) ** 2}
    for tag, xx in shapes.items():
        c = float((xx @ y) / (xx @ xx))
        r2 = 1.0 - float(((y - c * xx) ** 2).sum()) / float(((y - y.mean()) ** 2).sum())
        m.num(f"EsixInterpRsq{tag}", r2, 4)
    m.num("EsixInterpC", float((shapes["Log"] @ y) / (shapes["Log"] @ shapes["Log"])), 4)
    m.num("EsixGrowthGrid", per_d[-1]["s95"] / per_d[0]["s95"], 2)
    m.num("EsixGrowthInterp", interp[-1] / interp[0], 2)
    m.num("EsixGrowthPredicted",
          float((ds[-1] / np.log(ds[-1])) / (ds[0] / np.log(ds[0]))), 2)

    # Trial budget vs the confidence the point estimate can support at the largest width.
    top = per_d[-1]
    m.num("EsixTopBestWilsonLow", wilson_interval(top["trials"], top["trials"])[0], 3)
    m.integer("EsixEnergyTrialsTop", top["n_energy_trials"])
    return m


def main() -> None:
    m = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(m.render(), encoding="utf-8")
    print(f"wrote {len(m.items)} macros to {OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
